In [4]:
pip install --upgrade pip


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 33.8 MB/s eta 0:00:00
  Attempting uninstall: pip
    Found existing installation: pip 23.1.2
    Uninstalling pip-23.1.2:
      Successfully uninstalled pip-23.1.2


In [5]:
import tensorflow as tf
print(tf.__version__)

2.15.0


# word embeding

In [7]:
from tensorflow.keras.preprocessing.text import one_hot

In [31]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

## select vocabulary size for sentence

In [32]:
### Vocabulary size
voc_size=1000

In [33]:
onehot_repr = [one_hot(words, voc_size) for words in sent]

In [34]:
onehot_repr

[[63, 55, 585, 472],
 [63, 55, 585, 266],
 [63, 833, 585, 373],
 [29, 504, 328, 250, 631],
 [29, 504, 328, 250, 197],
 [134, 63, 157, 585, 662],
 [450, 492, 284, 250]]

## word embeddign representation

In [35]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence  import pad_sequences
from tensorflow.keras.models import Sequential
import pandas as pd

### padding

In [36]:
## pre padding   , define max length of padding

sent_length=10

In [37]:
embedded_docs = pad_sequences(onehot_repr , padding='pre' , maxlen=sent_length )

In [38]:
embedded_docs

array([[  0,   0,   0,   0,   0,   0,  63,  55, 585, 472],
       [  0,   0,   0,   0,   0,   0,  63,  55, 585, 266],
       [  0,   0,   0,   0,   0,   0,  63, 833, 585, 373],
       [  0,   0,   0,   0,   0,  29, 504, 328, 250, 631],
       [  0,   0,   0,   0,   0,  29, 504, 328, 250, 197],
       [  0,   0,   0,   0,   0, 134,  63, 157, 585, 662],
       [  0,   0,   0,   0,   0,   0, 450, 492, 284, 250]], dtype=int32)

### feature  dimentions

In [21]:
# now here we represent each abouve vector with number of n feature

# here we select  12

In [ ]:
dim = 12                                                                  # <-- we are represening 12 feature of each word

### create the model

In [23]:
model = Sequential()
model.add(Embedding(voc_size , 12 , input_length = sent_length ))
model.compile('adam' ,'mse')

In [24]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 10, 12)            12000     
                                                                 
Total params: 12000 (46.88 KB)
Trainable params: 12000 (46.88 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [27]:
##'the glass of milk',
embedded_docs[1]

array([  0,   0,   0,   0,   0,   0,  63,  55, 585, 266], dtype=int32)

In [28]:
model.predict(embedded_docs[1])     # here we have 10 word representation with each word have  12 dimention(feature)

1/1 [==============================] - 0s 117ms/step


array([[ 0.02395791,  0.00284358,  0.04868624, -0.02238731, -0.00964348,
        -0.0315155 , -0.04868368,  0.03720221,  0.02415097,  0.01978016,
         0.02969548, -0.01086744],
       [ 0.02395791,  0.00284358,  0.04868624, -0.02238731, -0.00964348,
        -0.0315155 , -0.04868368,  0.03720221,  0.02415097,  0.01978016,
         0.02969548, -0.01086744],
       [ 0.02395791,  0.00284358,  0.04868624, -0.02238731, -0.00964348,
        -0.0315155 , -0.04868368,  0.03720221,  0.02415097,  0.01978016,
         0.02969548, -0.01086744],
       [ 0.02395791,  0.00284358,  0.04868624, -0.02238731, -0.00964348,
        -0.0315155 , -0.04868368,  0.03720221,  0.02415097,  0.01978016,
         0.02969548, -0.01086744],
       [ 0.02395791,  0.00284358,  0.04868624, -0.02238731, -0.00964348,
        -0.0315155 , -0.04868368,  0.03720221,  0.02415097,  0.01978016,
         0.02969548, -0.01086744],
       [ 0.02395791,  0.00284358,  0.04868624, -0.02238731, -0.00964348,
        -0.0315155 , -

In [30]:
print(model.predict(embedded_docs) )

1/1 [==============================] - 0s 18ms/step
[[[ 0.02395791  0.00284358  0.04868624 -0.02238731 -0.00964348
   -0.0315155  -0.04868368  0.03720221  0.02415097  0.01978016
    0.02969548 -0.01086744]
  [ 0.02395791  0.00284358  0.04868624 -0.02238731 -0.00964348
   -0.0315155  -0.04868368  0.03720221  0.02415097  0.01978016
    0.02969548 -0.01086744]
  [ 0.02395791  0.00284358  0.04868624 -0.02238731 -0.00964348
   -0.0315155  -0.04868368  0.03720221  0.02415097  0.01978016
    0.02969548 -0.01086744]
  [ 0.02395791  0.00284358  0.04868624 -0.02238731 -0.00964348
   -0.0315155  -0.04868368  0.03720221  0.02415097  0.01978016
    0.02969548 -0.01086744]
  [ 0.02395791  0.00284358  0.04868624 -0.02238731 -0.00964348
   -0.0315155  -0.04868368  0.03720221  0.02415097  0.01978016
    0.02969548 -0.01086744]
  [ 0.02395791  0.00284358  0.04868624 -0.02238731 -0.00964348
   -0.0315155  -0.04868368  0.03720221  0.02415097  0.01978016
    0.02969548 -0.01086744]
  [-0.02780331  0.036839

#  new Way

In [40]:
from tensorflow.keras.layers import Embedding, Flatten, Dense
from tensorflow.keras.models import Sequential

# ...

# Create the model
model = Sequential()

# Add Embedding layer
model.add(Embedding(input_dim=voc_size, output_dim=12, input_length=sent_length))

# Flatten the embeddings
model.add(Flatten())                  # <-- : It simplifies the model structure,

# Add Dense layers for regression task
model.add(Dense(64, activation='relu'))
model.add(Dense(1, activation='linear'))  # Use 'linear' activation for regression if op is continues

# Compile the model
model.compile(optimizer='adam', loss='mse')  # Use mean squared error for regression

# Display model summary
model.summary()

# Predict using the model
predictions = model.predict(embedded_docs)
print(predictions)


Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 10, 12)            12000     
                                                                 
 flatten_1 (Flatten)         (None, 120)               0         
                                                                 
 dense_2 (Dense)             (None, 64)                7744      
                                                                 
 dense_3 (Dense)             (None, 1)                 65        
                                                                 
Total params: 19809 (77.38 KB)
Trainable params: 19809 (77.38 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
1/1 [==============================] - 0s 56ms/step
[[-0.00247085]
 [ 0.01160584]
 [-0.01232393]
 [ 0.00093636]
 [-0.00946833]
 [-0.01968632]
 [ 0.016

In [48]:


sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [49]:
from tensorflow.keras.preprocessing.text import one_hot

In [50]:
# step 1  = vocab size

vocab_size = 500

In [51]:
one_hot_repr =  [one_hot(word , vocab_size)for word in sent]

In [52]:
one_hot_repr

[[285, 355, 109, 234, 198, 260],
 [235, 311, 109, 33, 107, 277],
 [206, 44, 278, 87],
 [285, 298, 109, 148, 285, 469],
 [1, 180, 196, 109, 33, 107, 277],
 [478, 109, 33, 107, 15, 345]]

In [53]:
"Marvel series is my favourite movie"
one_hot_repr[1]

[235, 311, 109, 33, 107, 277]

In [55]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [59]:
sent_length = 10

In [60]:
embedded_doc =pad_sequences(one_hot_repr , maxlen=sent_length , padding='post' )

In [61]:
embedded_doc

array([[285, 355, 109, 234, 198, 260,   0,   0,   0,   0],
       [235, 311, 109,  33, 107, 277,   0,   0,   0,   0],
       [206,  44, 278,  87,   0,   0,   0,   0,   0,   0],
       [285, 298, 109, 148, 285, 469,   0,   0,   0,   0],
       [  1, 180, 196, 109,  33, 107, 277,   0,   0,   0],
       [478, 109,  33, 107,  15, 345,   0,   0,   0,   0]], dtype=int32)

In [63]:
#  feature dimention

fea_dimention = 15

In [ ]:
# word embeddding representation

## Word_embedding

In [65]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential

In [66]:
model= Sequential()

In [67]:
model.add(Embedding(input_dim=vocab_size , output_dim=fea_dimention ,input_length=sent_length))

model.add(Flatten())
model.add(Dense(64, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='mse')


model.summary()


Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 10, 15)            7500      
                                                                 
 flatten_2 (Flatten)         (None, 150)               0         
                                                                 
 dense_4 (Dense)             (None, 64)                9664      
                                                                 
 dense_5 (Dense)             (None, 1)                 65        
                                                                 
Total params: 17229 (67.30 KB)
Trainable params: 17229 (67.30 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [68]:
model.predict(embedded_doc)

1/1 [==============================] - 0s 158ms/step


array([[0.5108831 ],
       [0.50163484],
       [0.5023624 ],
       [0.50297314],
       [0.5026244 ],
       [0.50225806]], dtype=float32)